import assert from "node:assert";
import { describe, it } from "node:test";
import readFile from "../utils/readFile.ts";
import { part1, part2 } from "./day07.ts";

const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

const realInput = await readFile("src/days/day07-input.txt");

describe("2025 Day 07", () => {
  it.skip("should have the correct answers", () => {
    assert.equal(part1(realInput), 1698);
    assert.equal(part2(realInput), "");
  });

  it("should solve first part", () => {
    const result = part1(testInput);
    assert.equal(result, 21);
  });

  it("should solve second part", () => {
    const result = part2(testInput);
    assert.equal(result, 40);
  });
});
